data<- read.table("household_power_consumption.txt", skip=1,sep=";")
names(data) <- c("Date", "Time", "Global_active_power","Global_reactive_power", "Voltage", "Global_intensity","Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
subdata <-subset(data, data$Date == "1/2/2007" | data$Date == "2/2/2007")

daterange <- strptime(paste(subdata$Date, subdata$Time, sep = " "), "%d/%m/%Y %H:%M:%S")
metering1 <- as.numeric(subdata$Sub_metering_1)
metering2 <- as.numeric(subdata$Sub_metering_2)
metering3 <- as.numeric(subdata$Sub_metering_3)

png("plot3.png", width=480,height=480)
plot(daterange, metering1, type="l", ylab = "Energy Submetering")
lines(daterange, metering2, type ="l", col="red")
lines(daterange, metering3, type ="l",col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()
